# Generated by Django 4.1 on 2023-03-20 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unattended_object_detection_app', '0004_customuser_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='question',
            field=models.CharField(max_length=40),
        ),
    ]
