# Generated by Django 4.1 on 2023-04-01 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unattended_object_detection_app', '0005_alter_customuser_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='question',
        ),
    ]
