# Generated by Django 4.1 on 2023-04-01 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unattended_object_detection_app', '0006_remove_customuser_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='question',
            field=models.CharField(default='Vijayawada', max_length=40),
            preserve_default=False,
        ),
    ]
