# Generated by Django 4.1 on 2023-04-04 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unattended_object_detection_app', '0008_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=14),
        ),
    ]
